# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [test]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BUILD_ID: "$(date +'%Y%m%d')-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    # creating a build/release run number
      #- name: Build Number
       # run: echo "::set-env name=buildid::$(date +'%Y%m%d')-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER"
      
      - name: echo var
        run: echo env.BUILD_ID
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: output check
        id: outputcheck
        run: |
          OUTPUT="$(cat README.md)"
          echo "$OUTPUT"
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "$OUTPUT"
          echo "::set-output name=OUTPUT::$OUTPUT"
          
      - name: run if
        if: contains(steps.outputcheck.outputs.OUTPUT,'kuku')
        run: echo "kuku is here"
       
     
      - name: mkdir
        run: mkdir newDir
         
      - name: copy
        run: cp *.* newDir/
      - name: Run a multi-line script
        run: |
          cd newDir/
          ls
      - name: ls
        run: ls
           
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Replace tokens
          # You may pin to the exact commit or the version.
          # uses: cschleiden/replace-tokens@121d9153eda2951d490e9f724a67ff095ab4c4f7
        uses: cschleiden/replace-tokens@v1.0
        with:
          # 
          tokenPrefix: '{'
          # 
          tokenSuffix: '}'
          # 
          files: file.txt
        env:
          web: "this was replaced"
          dev: "second replace"
          
      - name: Run a one-line script
        run: cat file.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}
          # The desired behavior if no files are found using the provided path.  
          
