name: MergeToMain
on:
  workflow_dispatch:
  
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: test
      - name: merge dev to  main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: test
          target_branch: main
          github_token: ${{github.token}} 
      - name: Commit tagger
        # You may pin to the exact commit or the version.
        # uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d
        uses: tvdias/github-tagger@v0.0.2
        with:
          # The GITHUB_TOKEN secret
          repo-token: ${{github.token}} 
          # Tag text
          tag: "New Ver"# optional, default is 0.1.0
          # optional commit sha to apply the tag to
          #commit-sha: # optional
          
          
           # - uses : everlytic/branch-merge@1.1.2
           #   with: 
           #     github_token: ${{}}
           #     source_ref: 'dev'
           #     target_branch: 'main'
           #     commit_message_template: 'merged {source_ref} into target {target_branch}'

          
