name: MergeToMain
on:
  workflow_dispatch:
  
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: dev
      - name: merge dev to  main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{github.token}} 
          
     # - uses : everlytic/branch-merge@1.1.2
     #   with: 
     #     github_token: ${{}}
     #     source_ref: 'dev'
     #     target_branch: 'main'
     #     commit_message_template: 'merged {source_ref} into target {target_branch}'
          
          
