name: VariablesTest
on:
  workflow_dispatch:
  
jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set the value
        id: step_one
        run: |
          echo "sha=$(git log -1 --format="%H")" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.sha }}" # This will output 'yellow'
